logging:
  level:
    root: INFO
    com.azat.h1: DEBUG

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/todo_db}
    username: ${DB_USERNAME:todo_user}
    password: ${DB_PASSWORD:todo_password}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
