CREATE TABLE tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL,
    last_modified_at TIMESTAMP,
    due_date DATE,
    priority VARCHAR(20) NOT NULL
);

CREATE TABLE task_tags (
    task_id BIGINT NOT NULL,
    tag VARCHAR(255) NOT NULL,
    CONSTRAINT fk_task_tags_task
        FOREIGN KEY (task_id)
        REFERENCES tasks (id)
        ON DELETE CASCADE
);

CREATE TABLE task_attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    stored_file_name VARCHAR(255) NOT NULL UNIQUE,
    content_type VARCHAR(255),
    size BIGINT NOT NULL,
    uploaded_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_task_attachments_task
        FOREIGN KEY (task_id)
        REFERENCES tasks (id)
        ON DELETE CASCADE
);

CREATE INDEX idx_task_attachments_task_id ON task_attachments (task_id);

INSERT INTO tasks (title, description, completed, created_at, last_modified_at, due_date, priority)
VALUES
    ('Learn Spring', 'Study Spring Boot basics', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'MEDIUM'),
    ('Write Tests', 'Cover REST endpoints with tests', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'MEDIUM'),
    ('Finish Homework', 'Complete the To-Do List Manager project', FALSE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, 'MEDIUM');
